inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false
  
Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
    Exclude:
      - 'spec/**/*'
      
Metrics/AbcSize:
    Exclude:
      - 'spec/**/*'

Metrics/MethodLength:
    Exclude:
      - 'spec/**/*'
