language: ruby
cache: bundler
dist: trusty
sudo: false
rvm:
- 2.5.1
bundler_args: "--without development --path=~/.bundle"
before_script:
- bundle exec rake db:create db:migrate
script:
- "bundle exec rake"
- "bundle exec rubocop"
addons:
  postgresql: '9.6'
